# Generated by Django 5.1.2 on 2024-10-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
