# Generated by Django 5.1.2 on 2024-10-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signin', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
